### ISSUE TITLE
The last request - Transition

### ISSUE THREAD

**Issue by carmas123** [raven78/vue-resize-split-pane#10]
I've a problem.
To enable a transition when use the splitter with a collapsable left drawer we need to apply a css like this:
```
    .left-pane {
        transition: all .3s;
    }
```
before user press the toggle button and remove it after the .3s to restore the splitter sizable effects.

For now we don't have a prop to apply a custom class/style to left/right Pane.
My idea is to add two new props to component that mix the current "Pane column" class of panel with this prop.

**Comment by raven78** [comment]
Are you using one of the Panes as a drawer ?

If yes, then all you need is [State Transitions](https://vuejs.org/v2/guide/transitioning-state.html#ad) and use that technique to apply effects when changing the size of the Pane used as a drawer.

**Comment by carmas123** [comment]
Oh yes I want a left pane like a drawer but the only method that I know is with css I dont know how can I collapse or expand it with state transition

**Comment by raven78** [comment]
Set the `allow-resize = false` this hides the resize handler. You still can resize the pane using `size` prop.
Bind the `:size` to `animatedDrawerWidth`, change `drawerWidth` when user click hamburger and use state tansitions to change the width.  Your pane will resize.

Example:

```html
<template>
  <rs-pane :allow-resize="false" :size="animatedDrawerWidth" ...></rs-pane>
</template>

<script>
  export default {
    data() {
      return {
        drawerWidth: 0,
        tweenedDrawerWidth: 0


      }
    },
    computed: {
      animatedDrawerWidth: function () {
        return this.tweenedDrawerWidth.toFixed(0);
      }
    },
    watch: {
      drawerWidth: function (newValue) {
        TweenLite.to(this.$data, 0.5, { tweenedDrawerWidth: newValue }); // 0.5 is time
      }
    }
  }

</script>
```
You can look at [TweenLite](https://greensock.com/products/) to see easing and other options you have.
Or you can use [Tween](https://greensock.com/products/), the bigger library that can tween between 2 colors, do animations...

Take better look at vue docs  [State Transition](https://vuejs.org/v2/guide/transitioning-state.html#ad).
