### ISSUE TITLE
Using split-to rows doesn't flow panes correctly. 

### ISSUE THREAD

**Issue by bigredc2** [raven78/vue-resize-split-pane#18]
When using the first example but changing split-to to rows instead of columns it causes all the panes to stay in a line and not go down below each other.  Using the nested example works great.

**Comment by llpamies** [comment]
+1 I have the same problem.

**Comment by raven78** [comment]
@bigredc2, @llpamies can any of you switch to rows-bug branch and test that it works for you? 
Thank you.

**Comment by bigredc2** [comment]
Yeah I will try it tonight and let you know. Thanks

**Comment by bigredc2** [comment]
Yes it works there. Although I think the cursor is not working right now. It does not change to the resize cursor.

**Comment by raven78** [comment]
Great. 
Fixed the cursor...

A will update the npm package when I'll get some spare time.

Thank you.

**Comment by raven78** [comment]
updated the package on the npm to v0.1.5
