### ISSUE TITLE
Uncorrected problem when drag coordinates leave min/max size

### ISSUE THREAD

**Issue by jhlee8804** [raven78/vue-resize-split-pane#20]
### AS IS
![19_asis](https://user-images.githubusercontent.com/8110371/53933144-4bcba500-40e0-11e9-80f3-cfcf23b9f42a.gif)

### TO BE
![19_tobe](https://user-images.githubusercontent.com/8110371/53933178-70c01800-40e0-11e9-8f33-b9c4140a3eba.gif)

**Comment by raven78** [comment]
Thank you for taking the time to report and create a pull request for this.
All the best.
