### ISSUE TITLE
Add ability to change size programmatically

### ISSUE THREAD

**Issue by carmas123** [raven78/vue-resize-split-pane#4]
Hi, please can you add the ability to change size programmatically.
I see your code and I try to set the "size" prop programmatically but nothing.
Into Vue I try to set the localSize property and it work.

**Comment by raven78** [comment]
Update to latest version (0.0.6)
Bind size to your data.
When you change your data the primary pane will resize.

**Comment by carmas123** [comment]
This work fine, but now the rezied does not work.
This is my template code:
`<rs-panes :allow-resize="!shrink" :size="menuSize" :min-size="minMenuSize">`

**Comment by raven78** [comment]
Your template is OK.
I will release 0.0.7 in a bit, that will fix the problem.

**Comment by carmas123** [comment]
Thank you so much
