### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by carmas123** [raven78/vue-resize-split-pane#7]
Add ability to customize the "splitter" layout like color or size (width or height in horizontal mode).

**Comment by raven78** [comment]
This is a more involved change.

Can you elaborate on what you want to do ?

The color part has 2 colors, the color of the Resizer in normal state and the color on hover.
The size part, do you refer to the thickness of the Resizer? In normal or hover state?

**Comment by carmas123** [comment]
We can add some component properties like that:
resizerSize
resizerColor
resizerHoverSize
resizerHoverColor

and replace the style of class with a forced component props.

**Comment by raven78** [comment]
It's not just about propagating some props down the chain.
It involves some logic change too.

Newly added props are:
```js
resizerThikness: { type: Number, default: 2 }, // width of the resizer in px
resizerColor: { type: String, default: '#AAA' }, // any css color - if you set transparency, it will afect the border too
resizerBorderColor: { type: String, default: 'rgba(0,0,0, 0.15)' }, // any css color - #FFF, rgb(0,0,0), rgba(0,0,0,0)
resizerBorderThikness: { type: Number, default: 3 }, // border that forms the shadow px
```
I will push a new version soon.

**Comment by carmas123** [comment]
Wou...
